// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from 'C:/Applications/works/slick-form/node_modules/dumi/theme-default/slots/ContentFooter/index.js';
