// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { demos as dm0, frontmatter as fm0, toc as toc0, texts as txt0 } from 'C:/Applications/works/slick-form/docs/business/copy-label-content.md?type=meta';
import { demos as dm1, frontmatter as fm1, toc as toc1, texts as txt1 } from 'C:/Applications/works/slick-form/docs/form/anchor-card-form.md?type=meta';
import { demos as dm2, frontmatter as fm2, toc as toc2, texts as txt2 } from 'C:/Applications/works/slick-form/docs/form/editable-table.md?type=meta';
import { demos as dm3, frontmatter as fm3, toc as toc3, texts as txt3 } from 'C:/Applications/works/slick-form/docs/form/table-provider.md?type=meta';
import { demos as dm4, frontmatter as fm4, toc as toc4, texts as txt4 } from 'C:/Applications/works/slick-form/docs/form/page-provider.md?type=meta';
import { demos as dm5, frontmatter as fm5, toc as toc5, texts as txt5 } from 'C:/Applications/works/slick-form/docs/form/descriptions.md?type=meta';
import { demos as dm6, frontmatter as fm6, toc as toc6, texts as txt6 } from 'C:/Applications/works/slick-form/docs/form/anchor-card.md?type=meta';
import { demos as dm7, frontmatter as fm7, toc as toc7, texts as txt7 } from 'C:/Applications/works/slick-form/docs/form/create-form.md?type=meta';
import { demos as dm8, frontmatter as fm8, toc as toc8, texts as txt8 } from 'C:/Applications/works/slick-form/docs/form/create-spin.md?type=meta';
import { demos as dm9, frontmatter as fm9, toc as toc9, texts as txt9 } from 'C:/Applications/works/slick-form/docs/form/drawer-form.md?type=meta';
import { demos as dm10, frontmatter as fm10, toc as toc10, texts as txt10 } from 'C:/Applications/works/slick-form/docs/form/model-form.md?type=meta';
import { demos as dm11, frontmatter as fm11, toc as toc11, texts as txt11 } from 'C:/Applications/works/slick-form/docs/form/notice-bar.md?type=meta';
import { demos as dm12, frontmatter as fm12, toc as toc12, texts as txt12 } from 'C:/Applications/works/slick-form/docs/form/tab-drawer.md?type=meta';
import { demos as dm13, frontmatter as fm13, toc as toc13, texts as txt13 } from 'C:/Applications/works/slick-form/docs/form/table-list.md?type=meta';
import { demos as dm14, frontmatter as fm14, toc as toc14, texts as txt14 } from 'C:/Applications/works/slick-form/docs/business/index.md?type=meta';
import { demos as dm15, frontmatter as fm15, toc as toc15, texts as txt15 } from 'C:/Applications/works/slick-form/docs/form/card-form.md?type=meta';
import { demos as dm16, frontmatter as fm16, toc as toc16, texts as txt16 } from 'C:/Applications/works/slick-form/docs/form/drag-list.md?type=meta';
import { demos as dm17, frontmatter as fm17, toc as toc17, texts as txt17 } from 'C:/Applications/works/slick-form/docs/form/drag-tabs.md?type=meta';
import { demos as dm18, frontmatter as fm18, toc as toc18, texts as txt18 } from 'C:/Applications/works/slick-form/docs/form/long-text.md?type=meta';
import { demos as dm19, frontmatter as fm19, toc as toc19, texts as txt19 } from 'C:/Applications/works/slick-form/docs/form/step-form.md?type=meta';
import { demos as dm20, frontmatter as fm20, toc as toc20, texts as txt20 } from 'C:/Applications/works/slick-form/docs/form/ellipsis.md?type=meta';
import { demos as dm21, frontmatter as fm21, toc as toc21, texts as txt21 } from 'C:/Applications/works/slick-form/docs/form/advance.md?type=meta';
import { demos as dm22, frontmatter as fm22, toc as toc22, texts as txt22 } from 'C:/Applications/works/slick-form/docs/form/parsley.md?type=meta';
import { demos as dm23, frontmatter as fm23, toc as toc23, texts as txt23 } from 'C:/Applications/works/slick-form/docs/form/button.md?type=meta';
import { demos as dm24, frontmatter as fm24, toc as toc24, texts as txt24 } from 'C:/Applications/works/slick-form/docs/form/search.md?type=meta';
import { demos as dm25, frontmatter as fm25, toc as toc25, texts as txt25 } from 'C:/Applications/works/slick-form/docs/tools/index.md?type=meta';
import { demos as dm26, frontmatter as fm26, toc as toc26, texts as txt26 } from 'C:/Applications/works/slick-form/docs/form/index.md?type=meta';
import { demos as dm27, frontmatter as fm27, toc as toc27, texts as txt27 } from 'C:/Applications/works/slick-form/docs/form/base.md?type=meta';
import { demos as dm28, frontmatter as fm28, toc as toc28, texts as txt28 } from 'C:/Applications/works/slick-form/docs/form/grid.md?type=meta';
import { demos as dm29, frontmatter as fm29, toc as toc29, texts as txt29 } from 'C:/Applications/works/slick-form/docs/index.md?type=meta';

export { components } from './atoms';
export { tabs } from './tabs';

export const filesMeta = {
  'docs/business/copy-label-content': {
    frontmatter: fm0,
    toc: toc0,
    texts: txt0,
    demos: dm0,
  },
  'docs/form/anchor-card-form': {
    frontmatter: fm1,
    toc: toc1,
    texts: txt1,
    demos: dm1,
  },
  'docs/form/editable-table': {
    frontmatter: fm2,
    toc: toc2,
    texts: txt2,
    demos: dm2,
  },
  'docs/form/table-provider': {
    frontmatter: fm3,
    toc: toc3,
    texts: txt3,
    demos: dm3,
  },
  'docs/form/page-provider': {
    frontmatter: fm4,
    toc: toc4,
    texts: txt4,
    demos: dm4,
  },
  'docs/form/descriptions': {
    frontmatter: fm5,
    toc: toc5,
    texts: txt5,
    demos: dm5,
  },
  'docs/form/anchor-card': {
    frontmatter: fm6,
    toc: toc6,
    texts: txt6,
    demos: dm6,
  },
  'docs/form/create-form': {
    frontmatter: fm7,
    toc: toc7,
    texts: txt7,
    demos: dm7,
  },
  'docs/form/create-spin': {
    frontmatter: fm8,
    toc: toc8,
    texts: txt8,
    demos: dm8,
  },
  'docs/form/drawer-form': {
    frontmatter: fm9,
    toc: toc9,
    texts: txt9,
    demos: dm9,
  },
  'docs/form/model-form': {
    frontmatter: fm10,
    toc: toc10,
    texts: txt10,
    demos: dm10,
  },
  'docs/form/notice-bar': {
    frontmatter: fm11,
    toc: toc11,
    texts: txt11,
    demos: dm11,
  },
  'docs/form/tab-drawer': {
    frontmatter: fm12,
    toc: toc12,
    texts: txt12,
    demos: dm12,
  },
  'docs/form/table-list': {
    frontmatter: fm13,
    toc: toc13,
    texts: txt13,
    demos: dm13,
  },
  'docs/business/index': {
    frontmatter: fm14,
    toc: toc14,
    texts: txt14,
    demos: dm14,
  },
  'docs/form/card-form': {
    frontmatter: fm15,
    toc: toc15,
    texts: txt15,
    demos: dm15,
  },
  'docs/form/drag-list': {
    frontmatter: fm16,
    toc: toc16,
    texts: txt16,
    demos: dm16,
  },
  'docs/form/drag-tabs': {
    frontmatter: fm17,
    toc: toc17,
    texts: txt17,
    demos: dm17,
  },
  'docs/form/long-text': {
    frontmatter: fm18,
    toc: toc18,
    texts: txt18,
    demos: dm18,
  },
  'docs/form/step-form': {
    frontmatter: fm19,
    toc: toc19,
    texts: txt19,
    demos: dm19,
  },
  'docs/form/ellipsis': {
    frontmatter: fm20,
    toc: toc20,
    texts: txt20,
    demos: dm20,
  },
  'docs/form/advance': {
    frontmatter: fm21,
    toc: toc21,
    texts: txt21,
    demos: dm21,
  },
  'docs/form/parsley': {
    frontmatter: fm22,
    toc: toc22,
    texts: txt22,
    demos: dm22,
  },
  'docs/form/button': {
    frontmatter: fm23,
    toc: toc23,
    texts: txt23,
    demos: dm23,
  },
  'docs/form/search': {
    frontmatter: fm24,
    toc: toc24,
    texts: txt24,
    demos: dm24,
  },
  'docs/tools/index': {
    frontmatter: fm25,
    toc: toc25,
    texts: txt25,
    demos: dm25,
  },
  'docs/form/index': {
    frontmatter: fm26,
    toc: toc26,
    texts: txt26,
    demos: dm26,
  },
  'docs/form/base': {
    frontmatter: fm27,
    toc: toc27,
    texts: txt27,
    demos: dm27,
  },
  'docs/form/grid': {
    frontmatter: fm28,
    toc: toc28,
    texts: txt28,
    demos: dm28,
  },
  'docs/index': {
    frontmatter: fm29,
    toc: toc29,
    texts: txt29,
    demos: dm29,
  },
}

// generate demos data in runtime, for reuse route.id to reduce bundle size
export const demos = Object.entries(filesMeta).reduce((acc, [id, meta]) => {
  // append route id to demo
  Object.values(meta.demos).forEach((demo) => {
    demo.routeId = id;
  });
  // merge demos
  Object.assign(acc, meta.demos);

  // remove demos from meta, to avoid deep clone demos in umi routes/children compatible logic
  delete meta.demos;

  return acc;
}, {});
