name: Build and Deploy Documentation

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Configure npm registry to Taobao mirror
      run: npm config set registry https://registry.npm.taobao.org

    - name: Build Documentation
      run: npm run build:docs

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: documentation
        path: ./docs-dist

